/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function compilePost(postFile: string, monthFolder: string): JsPost | null

export declare function compilePosts(postsDir: string): JsContentManifest

export interface JsContentManifest {
  posts: Array<JsPost>
  publicPosts: Array<JsPost>
}

export interface JsFrontmatterEntry {
  key: string
  value: string
}

export interface JsPost {
  id: string
  content: string
  monthFolder: string
  isDraft: boolean
  isHidden: boolean
  title: string
  date: string
  description: string
  tags: Array<string>
  author: string
  noToc?: boolean
  toc: Array<JsTocItem>
  extra: Array<JsFrontmatterEntry>
}

export interface JsTocItem {
  id: string
  text: string
  level: number
}

export declare function version(): string
