import crypto from 'node:crypto';
import { watch, type FSWatcher } from 'node:fs';
import fs from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';

const require = createRequire(import.meta.url);

const NATIVE_BINDING_CANDIDATES = [
  '../garden-content-compiler.node',
  '../garden-content-compiler.darwin-arm64.node',
  '@elecmonkey/garden-content-compiler-darwin-arm64',
  '../garden-content-compiler.linux-x64-gnu.node',
  '@elecmonkey/garden-content-compiler-linux-x64-gnu',
  '../garden-content-compiler.linux-x64-musl.node',
  '@elecmonkey/garden-content-compiler-linux-x64-musl',
] as const;

const PACKAGE_CANDIDATE_PREFIX = '@elecmonkey/garden-content-compiler-';

function nativeBindingLoadError(lastError?: unknown): Error {
  const message = [
    'garden-content-compiler native binding is not built for this platform.',
    'Run `pnpm --filter @elecmonkey/garden-content-compiler build`.',
    `Last lookup: ${displayNativeBindingCandidate(NATIVE_BINDING_CANDIDATES[NATIVE_BINDING_CANDIDATES.length - 1])}`,
  ].join(' ');

  if (lastError instanceof Error && lastError.message) {
    return new Error(`${message} ${lastError.message}`);
  }

  return new Error(message);
}

function displayNativeBindingCandidate(candidate: string): string {
  return candidate.startsWith(PACKAGE_CANDIDATE_PREFIX)
    ? candidate
    : path.basename(candidate);
}

function loadNativeBinding(): NativeBinding {
  let lastError: unknown;

  for (const candidate of NATIVE_BINDING_CANDIDATES) {
    try {
      return require(candidate) as NativeBinding;
    } catch (error) {
      lastError = error;
    }
  }

  return {
    version() {
      return '0.0.0';
    },
    compilePost() {
      throw nativeBindingLoadError(lastError);
    },
    compilePosts() {
      throw nativeBindingLoadError(lastError);
    },
  };
}

const CACHE_VERSION = 2;
const SCHEMA_VERSION = 5;
const DEFAULT_GENERATED_HEADER = '/* This file is generated by @elecmonkey/garden-content-compiler. Do not edit manually. */';

type RsbuildPlugin = {
  name: string;
  enforce: 'pre';
  setup(api: RsbuildPluginApi): void;
};

type RsbuildPluginApi = {
  context: {
    rootPath?: string;
  };
  logger?: Logger;
  onBeforeBuild(hook: HookDescriptor<(params: { isFirstCompile: boolean }) => Promise<void> | void>): void;
  onBeforeStartDevServer(hook: HookDescriptor<(params: { server: DevServer }) => Promise<void> | void>): void;
  onCloseDevServer(hook: () => void): void;
};

type HookDescriptor<T> = {
  order: 'pre';
  handler: T;
};

type DevServer = {
  middlewares: {
    use(route: string, handler: (req: RequestLike, res: ServerResponseLike) => Promise<void> | void): void;
  };
};

type RequestLike = {
  url?: string;
};

type ServerResponseLike = {
  statusCode: number;
  setHeader(name: string, value: string): void;
  end(body: string | Buffer): void;
};

type Logger = {
  info(message: string): void;
  error(error: unknown): void;
};

export interface JsContentManifest {
  posts: JsPost[];
  publicPosts: JsPost[];
}

export type LocaleCode = 'zh' | 'en' | (string & {});

export interface LocaleContentOptions {
  postsDirectory: string;
  urlPrefix?: string;
}

export interface JsFrontmatterEntry {
  key: string;
  value: string;
}

export interface JsPost {
  locale?: string;
  id: string;
  content: string;
  html: string;
  islands: JsMarkdownIsland[];
  searchContent: string;
  monthFolder: string;
  isDraft: boolean;
  isHidden: boolean;
  title: string;
  date: string;
  description: string;
  tags: string[];
  author: string;
  noToc?: boolean;
  toc: JsTocItem[];
  extra: JsFrontmatterEntry[];
}

export interface JsMarkdownIsland {
  kind: 'code' | 'mermaid' | 'graphviz' | 'file-download';
  id: string;
  language?: string;
  range?: string;
  filename?: string;
  fileType?: string;
  url?: string;
  size?: string;
  scale?: number;
}

export interface JsTocItem {
  id: string;
  text: string;
  level: number;
}

type NativeBinding = {
  compilePost(postFile: string, monthFolder: string): JsPost | null;
  compilePosts(postsDir: string): JsContentManifest;
  version(): string;
};

type NormalizedPost = Omit<JsPost, 'noToc' | 'extra'> & {
  locale: string;
  permalink: string;
  prevPost?: { id: string; title: string };
  nextPost?: { id: string; title: string };
  no_toc?: boolean;
  [key: string]: unknown;
};

type PostWithMeta = NormalizedPost & {
  sourceKey: string;
  sourceHash: string;
  contentHash: string;
};

type CacheManifestEntry = {
  locale: string;
  slug: string;
  monthFolder: string;
  hash: string;
  contentHash: string;
  cacheFile: string;
};

type CacheManifest = {
  version: number;
  compilerVersion: string;
  schemaVersion: number;
  posts: Record<string, CacheManifestEntry>;
};

type ResolvedGenerateContentOptions = Required<Pick<
  GenerateContentOptions,
  'root' | 'generatedDirectory' | 'generatedPostsDirectory' | 'outputFile' | 'cacheDirectory' | 'typeImport' | 'generatedHeader' | 'log'
>> & {
  locales: ResolvedLocaleContentOptions[];
  cacheManifestFile: string;
};

type ResolvedLocaleContentOptions = {
  locale: string;
  postsDirectory: string;
  urlPrefix: string;
  searchIndexFile: string;
  cachePostsDirectory: string;
};

export interface GenerateContentOptions {
  root?: string;
  postsDirectory?: string;
  locales?: Record<string, LocaleContentOptions>;
  generatedDirectory?: string;
  generatedPostsDirectory?: string;
  outputFile?: string;
  searchIndexFile?: string;
  cacheDirectory?: string;
  typeImport?: string;
  generatedHeader?: string;
  log?: boolean;
}

export interface GenerateContentResult {
  posts: PostWithMeta[];
  postCountByLocale: Record<string, number>;
  postCount: number;
  compiledCount: number;
  reusedCount: number;
  changedPostModules: number;
  contentChanged: boolean;
  searchChanged: boolean;
  root: string;
  outputFile: string;
  searchIndexFiles: Record<string, string>;
  compilerVersion: string;
}

export interface GardenContentPluginOptions extends GenerateContentOptions {
  watch?: boolean;
  serveSearchIndex?: boolean;
  searchIndexRoute?: string;
}

const nativeBinding = loadNativeBinding();

export const compilePost = nativeBinding.compilePost;
export const compilePosts = nativeBinding.compilePosts;
export const version = nativeBinding.version;

function toSearchIndexPost(post: NormalizedPost) {
  return {
    locale: post.locale,
    id: post.id,
    title: post.title,
    date: post.date,
    description: post.description,
    tags: post.tags,
    author: post.author,
    content: post.searchContent || '',
  };
}

function toPermalink(localeOptions: ResolvedLocaleContentOptions, slug: string): string {
  const prefix = localeOptions.urlPrefix.replace(/\/+$/g, '');
  return `${prefix}/blog/${slug}`;
}

function normalizePost(post: JsPost, localeOptions: ResolvedLocaleContentOptions): NormalizedPost {
  const {
    monthFolder,
    isDraft,
    isHidden,
    noToc,
    extra = [],
    ...rest
  } = post;

  const extraFields = Object.fromEntries(
    extra.map(({ key, value }) => [key, value]),
  );

  return {
    ...rest,
    locale: localeOptions.locale,
    permalink: toPermalink(localeOptions, rest.id),
    monthFolder,
    isDraft,
    isHidden,
    ...(noToc === undefined ? {} : { no_toc: noToc }),
    ...extraFields,
  };
}

function isDraftMarkdown(fileName: string): boolean {
  return fileName.endsWith('.md') && fileName.startsWith('draft-');
}

function isPostMarkdown(fileName: string): boolean {
  return fileName.endsWith('.md') && !isDraftMarkdown(fileName);
}

function fileHash(source: string | NodeJS.ArrayBufferView): string {
  return `sha256:${crypto.createHash('sha256').update(source).digest('hex')}`;
}

function postContentHash(post: NormalizedPost): string {
  const { searchContent: _searchContent, ...generatedPost } = post;
  return fileHash(JSON.stringify(generatedPost));
}

function toPosixPath(value: string): string {
  return value.split(path.sep).join('/');
}

function resolveLocales(root: string, options: GenerateContentOptions): ResolvedLocaleContentOptions[] {
  const rawLocales = options.locales ?? {
    zh: {
      postsDirectory: options.postsDirectory || 'src/content/posts',
      urlPrefix: '',
    },
  };

  return Object.entries(rawLocales).map(([locale, localeOptions]) => ({
    locale,
    postsDirectory: path.resolve(root, localeOptions.postsDirectory),
    urlPrefix: localeOptions.urlPrefix ?? (locale === 'en' ? '/en' : ''),
    searchIndexFile: path.resolve(root, options.generatedDirectory || 'src/generated', `search-index.${locale}.json`),
    cachePostsDirectory: path.resolve(root, options.cacheDirectory || '.garden-cache/content', 'posts', locale),
  }));
}

function resolveOptions(options: GenerateContentOptions = {}): ResolvedGenerateContentOptions {
  const root = path.resolve(options.root || process.cwd());
  const generatedDirectory = path.resolve(root, options.generatedDirectory || 'src/generated');
  const generatedPostsDirectory = path.resolve(generatedDirectory, options.generatedPostsDirectory || 'posts');
  const outputFile = path.resolve(generatedDirectory, options.outputFile || 'content.ts');
  const cacheDirectory = path.resolve(root, options.cacheDirectory || '.garden-cache/content');
  const cacheManifestFile = path.resolve(cacheDirectory, 'manifest.json');
  const locales = resolveLocales(root, { ...options, generatedDirectory, cacheDirectory });

  return {
    root,
    locales,
    generatedDirectory,
    generatedPostsDirectory,
    outputFile,
    cacheDirectory,
    cacheManifestFile,
    typeImport: options.typeImport || '@/lib/api',
    generatedHeader: options.generatedHeader || DEFAULT_GENERATED_HEADER,
    log: options.log !== false,
  };
}

function toSourceKey(options: ResolvedGenerateContentOptions, filePath: string): string {
  return toPosixPath(path.relative(options.root, filePath));
}

function toCacheFile(locale: string, slug: string): string {
  return `posts/${locale}/${slug}.json`;
}

function toGeneratedPostFile(options: ResolvedGenerateContentOptions, locale: string, slug: string): string {
  return path.join(options.generatedPostsDirectory, locale, `${slug}.ts`);
}

async function pathExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function readJsonFile<T>(filePath: string, fallback: T): Promise<T> {
  try {
    return JSON.parse(await fs.readFile(filePath, 'utf8')) as T;
  } catch {
    return fallback;
  }
}

async function writeFileIfChanged(filePath: string, content: string): Promise<boolean> {
  try {
    const current = await fs.readFile(filePath, 'utf8');
    if (current === content) {
      return false;
    }
  } catch {
    // New file.
  }

  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content);
  return true;
}

async function removeIfExists(filePath: string): Promise<void> {
  try {
    await fs.rm(filePath, { force: true });
  } catch {
    // Nothing to remove.
  }
}

async function scanPostFiles(directory: string): Promise<string[]> {
  const files: string[] = [];
  const entries = await fs.readdir(directory, { withFileTypes: true });

  for (const entry of entries) {
    const entryPath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...await scanPostFiles(entryPath));
      continue;
    }

    if (entry.isFile() && isPostMarkdown(entry.name)) {
      files.push(entryPath);
    }
  }

  return files.sort().reverse();
}

function createEmptyManifest(): CacheManifest {
  return {
    version: CACHE_VERSION,
    compilerVersion: version(),
    schemaVersion: SCHEMA_VERSION,
    posts: {},
  };
}

function isUsableManifest(manifest: unknown): manifest is CacheManifest {
  return Boolean(
    manifest
    && typeof manifest === 'object'
    && (manifest as CacheManifest).version === CACHE_VERSION
    && (manifest as CacheManifest).compilerVersion === version()
    && (manifest as CacheManifest).schemaVersion === SCHEMA_VERSION
    && (manifest as CacheManifest).posts
    && typeof (manifest as CacheManifest).posts === 'object',
  );
}

async function readCachePost(options: ResolvedGenerateContentOptions, cacheFile: string): Promise<NormalizedPost | undefined> {
  const cachePath = path.join(options.cacheDirectory, cacheFile);
  return readJsonFile<NormalizedPost | undefined>(cachePath, undefined);
}

async function writeCachePost(options: ResolvedGenerateContentOptions, cacheFile: string, post: NormalizedPost): Promise<void> {
  const cachePath = path.join(options.cacheDirectory, cacheFile);
  await writeFileIfChanged(cachePath, `${JSON.stringify(post)}\n`);
}

function addPostNavigation(posts: PostWithMeta[]): PostWithMeta[] {
  const publicPosts = posts.filter((post) => !post.isHidden && !post.isDraft);
  const navigationById = new Map<string, Pick<NormalizedPost, 'prevPost' | 'nextPost'>>();

  publicPosts.forEach((post, index) => {
    const previous = publicPosts[index + 1];
    const next = publicPosts[index - 1];
    navigationById.set(post.id, {
      prevPost: previous ? { id: previous.id, title: previous.title } : undefined,
      nextPost: next ? { id: next.id, title: next.title } : undefined,
    });
  });

  return posts.map((post) => ({
    ...post,
    ...navigationById.get(post.id),
  }));
}

async function buildPostsWithCache(options: ResolvedGenerateContentOptions): Promise<{
  posts: PostWithMeta[];
  compiledCount: number;
  reusedCount: number;
}> {
  const cachedManifest = await readJsonFile<unknown>(options.cacheManifestFile, undefined);
  const previousManifest = isUsableManifest(cachedManifest) ? cachedManifest : createEmptyManifest();
  const nextManifest = createEmptyManifest();
  const posts: PostWithMeta[] = [];
  let compiledCount = 0;
  let reusedCount = 0;

  for (const localeOptions of options.locales) {
    const postFiles = await scanPostFiles(localeOptions.postsDirectory);
    const localePosts: PostWithMeta[] = [];

    await fs.mkdir(localeOptions.cachePostsDirectory, { recursive: true });

    for (const filePath of postFiles) {
      const source = await fs.readFile(filePath);
      const hash = fileHash(source);
      const sourceKey = `${localeOptions.locale}:${toSourceKey(options, filePath)}`;
      const monthFolder = path.basename(path.dirname(filePath));
      const previousEntry = previousManifest.posts[sourceKey];
      let post: NormalizedPost | undefined;

      if (previousEntry?.hash === hash && previousEntry.locale === localeOptions.locale) {
        post = await readCachePost(options, previousEntry.cacheFile);
      }

      if (post) {
        reusedCount += 1;
      } else {
        const compiledPost = compilePost(filePath, monthFolder);
        if (!compiledPost) {
          continue;
        }
        post = normalizePost(compiledPost, localeOptions);
        compiledCount += 1;
      }

      const cacheFile = toCacheFile(localeOptions.locale, post.id);
      const contentHash = postContentHash(post);
      await writeCachePost(options, cacheFile, post);

      nextManifest.posts[sourceKey] = {
        locale: localeOptions.locale,
        slug: post.id,
        monthFolder,
        hash,
        contentHash,
        cacheFile,
      };
      localePosts.push({ ...post, sourceKey, sourceHash: hash, contentHash });
    }

    localePosts.sort((a, b) => b.date.localeCompare(a.date));
    posts.push(...addPostNavigation(localePosts));
  }

  const activeCacheFiles = new Set(
    Object.values(nextManifest.posts).map((entry) => entry.cacheFile),
  );

  for (const entry of Object.values(previousManifest.posts)) {
    if (!activeCacheFiles.has(entry.cacheFile)) {
      await removeIfExists(path.join(options.cacheDirectory, entry.cacheFile));
    }
  }

  await writeFileIfChanged(options.cacheManifestFile, `${JSON.stringify(nextManifest, null, 2)}\n`);

  return { posts, compiledCount, reusedCount };
}

function createPostModule(options: ResolvedGenerateContentOptions, postWithMeta: PostWithMeta): string {
  const { searchContent: _searchContent, sourceHash, contentHash, sourceKey: _sourceKey, ...post } = postWithMeta;

  return `${options.generatedHeader}\n\n`
    + `import type { PostData } from '${options.typeImport}';\n\n`
    + `export const postSourceHash = ${JSON.stringify(sourceHash)};\n`
    + `export const postContentHash = ${JSON.stringify(contentHash)};\n\n`
    + `export const post = ${JSON.stringify(post, null, 2)} satisfies PostData;\n`;
}

function toPostMetadata(postWithMeta: PostWithMeta): Omit<PostWithMeta, 'content' | 'html' | 'islands' | 'searchContent' | 'toc' | 'sourceKey' | 'sourceHash' | 'contentHash'> {
  const {
    content: _content,
    html: _html,
    islands: _islands,
    searchContent: _searchContent,
    toc: _toc,
    sourceKey: _sourceKey,
    sourceHash: _sourceHash,
    contentHash: _contentHash,
    ...post
  } = postWithMeta;

  return post;
}

function createHomeModule(options: ResolvedGenerateContentOptions, posts: PostWithMeta[]): string {
  const locales = Array.from(new Set(posts.map((post) => post.locale)));
  const contentByLocale = Object.fromEntries(locales.map((locale) => {
    const localePosts = posts.filter((post) => post.locale === locale);
    const publicPosts = localePosts.filter((post) => !post.isHidden && !post.isDraft);
    const recentPosts = publicPosts.slice(0, 8).map(toPostMetadata);
    const tagCounts = new Map<string, number>();

    for (const post of publicPosts) {
      for (const tag of post.tags) {
        tagCounts.set(tag, (tagCounts.get(tag) ?? 0) + 1);
      }
    }

    const tags = Array.from(tagCounts, ([name, count]) => ({ name, count }))
      .sort((a, b) => a.name.localeCompare(b.name, 'en'));
    const latestUpdateDate = publicPosts[0]?.date ?? null;

    return [locale, {
      recentPosts,
      tags,
      stats: { totalPosts: publicPosts.length, latestUpdateDate },
    }];
  }));

  return `${options.generatedHeader}

`
    + `import type { HomeContentByLocale } from '${options.typeImport}';

`
    + `export const generatedHomeContentByLocale = ${JSON.stringify(contentByLocale, null, 2)} satisfies HomeContentByLocale;
`;
}

function createContentModule(options: ResolvedGenerateContentOptions, posts: PostWithMeta[]): string {
  const locales = Array.from(new Set(posts.map((post) => post.locale)));
  const localeEntries = locales.map((locale) => {
    const localePosts = posts.filter((post) => post.locale === locale);
    const postList = localePosts
      .map((post) => `      ${JSON.stringify(toPostMetadata(post), null, 2).replace(/\n/g, '\n      ')},`)
      .join('\n');
    const hashList = localePosts
      .map((post) => (
        `      ${JSON.stringify(post.id)}: { sourceHash: ${JSON.stringify(post.sourceHash)}, contentHash: ${JSON.stringify(post.contentHash)} },`
      ))
      .join('\n');
    const loaderList = localePosts
      .map((post) => `      ${JSON.stringify(post.id)}: () => import('./posts/${locale}/${post.id}'),`)
      .join('\n');

    return `  ${JSON.stringify(locale)}: {
    posts: [
${postList}
    ],
    publicPosts: [
${localePosts.filter((post) => !post.isHidden).map((post) => `      ${JSON.stringify(toPostMetadata(post), null, 2).replace(/\n/g, '\n      ')},`).join('\n')}
    ],
    postHashes: {
${hashList}
    },
    postLoaders: {
${loaderList}
    },
  },`;
  }).join('\n');

  return `${options.generatedHeader}\n\n`
    + `import type { GeneratedContentByLocale } from '${options.typeImport}';\n\n`
    + `export const generatedContentByLocale = {\n${localeEntries}\n} satisfies GeneratedContentByLocale;\n`;
}

async function cleanupStaleGeneratedPosts(options: ResolvedGenerateContentOptions, activeFiles: Set<string>): Promise<void> {
  if (!await pathExists(options.generatedPostsDirectory)) {
    return;
  }

  async function cleanupDirectory(directory: string): Promise<void> {
    const entries = await fs.readdir(directory, { withFileTypes: true });
    await Promise.all(entries.map(async (entry) => {
      const entryPath = path.join(directory, entry.name);
      if (entry.isDirectory()) {
        await cleanupDirectory(entryPath);
        return;
      }

      if (!entry.isFile() || !entry.name.endsWith('.ts')) {
        return;
      }

      if (!activeFiles.has(toPosixPath(path.relative(options.generatedPostsDirectory, entryPath)))) {
        await removeIfExists(entryPath);
      }
    }));
  }

  await cleanupDirectory(options.generatedPostsDirectory);
}

async function writeGeneratedFiles(options: ResolvedGenerateContentOptions, posts: PostWithMeta[]): Promise<{
  changedPostModules: number;
  contentChanged: boolean;
  searchChanged: boolean;
}> {
  await fs.mkdir(options.generatedPostsDirectory, { recursive: true });

  const activeFiles = new Set(posts.map((post) => `${post.locale}/${post.id}.ts`));
  await cleanupStaleGeneratedPosts(options, activeFiles);

  let changedPostModules = 0;
  for (const post of posts) {
    const changed = await writeFileIfChanged(toGeneratedPostFile(options, post.locale, post.id), createPostModule(options, post));
    if (changed) {
      changedPostModules += 1;
    }
  }

  const contentChanged = await writeFileIfChanged(options.outputFile, createContentModule(options, posts));
  const homeChanged = await writeFileIfChanged(path.join(options.generatedDirectory, 'home.ts'), createHomeModule(options, posts));
  let searchChanged = false;

  for (const localeOptions of options.locales) {
    const publicPosts = posts.filter((post) => post.locale === localeOptions.locale && !post.isHidden);
    const searchIndex = publicPosts.map(toSearchIndexPost);
    searchChanged = await writeFileIfChanged(localeOptions.searchIndexFile, JSON.stringify(searchIndex)) || searchChanged;
  }

  return { changedPostModules, contentChanged: contentChanged || homeChanged, searchChanged };
}

export async function generateContent(rawOptions: GenerateContentOptions = {}): Promise<GenerateContentResult> {
  const options = resolveOptions(rawOptions);
  const { posts, compiledCount, reusedCount } = await buildPostsWithCache(options);
  const { changedPostModules, contentChanged, searchChanged } = await writeGeneratedFiles(options, posts);
  const postCountByLocale = Object.fromEntries(
    options.locales.map((localeOptions) => [
      localeOptions.locale,
      posts.filter((post) => post.locale === localeOptions.locale).length,
    ]),
  );
  const searchIndexFiles = Object.fromEntries(
    options.locales.map((localeOptions) => [localeOptions.locale, localeOptions.searchIndexFile]),
  );
  const result: GenerateContentResult = {
    posts,
    postCountByLocale,
    postCount: posts.length,
    compiledCount,
    reusedCount,
    changedPostModules,
    contentChanged,
    searchChanged,
    root: options.root,
    outputFile: options.outputFile,
    searchIndexFiles,
    compilerVersion: version(),
  };

  if (options.log) {
    console.log(formatContentResult(result));
    if (contentChanged || searchChanged) {
      console.log(`updated indexes: content=${contentChanged}, search=${searchChanged}`);
    }
  }

  return result;
}

function formatContentResult(result: GenerateContentResult): string {
  const localeCounts = Object.entries(result.postCountByLocale)
    .map(([locale, count]) => `${locale}=${count}`)
    .join(', ');
  const searchFiles = Object.values(result.searchIndexFiles)
    .map((filePath) => path.relative(result.root, filePath))
    .join(', ');

  return `generated ${result.postCount} posts `
    + `(${localeCounts}) `
    + `(${result.compiledCount} compiled, ${result.reusedCount} cached, ${result.changedPostModules} post modules changed) `
    + `to ${path.relative(result.root, result.outputFile)} and ${searchFiles} `
    + `with content compiler ${result.compilerVersion}`;
}

function createContentWatcher(pluginOptions: GenerateContentOptions, run: () => Promise<GenerateContentResult>, logger: Logger): () => void {
  const options = resolveOptions(pluginOptions);
  let timer: ReturnType<typeof setTimeout> | undefined;
  let running = false;
  let pending = false;
  const watchers: FSWatcher[] = [];

  const rerun = () => {
    if (running) {
      pending = true;
      return;
    }

    running = true;
    void run()
      .catch((error: unknown) => {
        logger.error(error);
      })
      .finally(() => {
        running = false;
        if (pending) {
          pending = false;
          rerun();
        }
      });
  };

  for (const localeOptions of options.locales) {
    const watcher: FSWatcher = watch(localeOptions.postsDirectory, { recursive: true }, (_eventType, fileName) => {
      if (!fileName || !fileName.endsWith('.md')) {
        return;
      }

      if (timer) {
        clearTimeout(timer);
      }

      timer = setTimeout(rerun, 80);
    });

    watcher.on('error', (error) => {
      logger.error(error);
    });
    watchers.push(watcher);
  }

  return () => {
    if (timer) {
      clearTimeout(timer);
    }
    for (const watcher of watchers) {
      watcher.close();
    }
  };
}

export function gardenContentPlugin(rawOptions: GardenContentPluginOptions = {}): RsbuildPlugin {
  const pluginOptions = { ...rawOptions };
  const shouldWatch = pluginOptions.watch !== false;
  const serveSearchIndex = pluginOptions.serveSearchIndex !== false;
  let closeWatcher: (() => void) | undefined;

  return {
    name: 'garden-content-plugin',
    enforce: 'pre',
    setup(api) {
      const logger = api.logger || console;
      const resolvePluginOptions = (): GenerateContentOptions => ({
        ...pluginOptions,
        root: pluginOptions.root || api.context.rootPath || process.cwd(),
        log: false,
      });
      const run = async () => {
        const result = await generateContent(resolvePluginOptions());
        logger.info(formatContentResult(result));
        if (result.contentChanged || result.searchChanged) {
          logger.info(`updated indexes: content=${result.contentChanged}, search=${result.searchChanged}`);
        }
        return result;
      };

      api.onBeforeBuild({
        order: 'pre',
        handler: async ({ isFirstCompile }) => {
          if (!isFirstCompile) {
            return;
          }
          await run();
        },
      });

      api.onBeforeStartDevServer({
        order: 'pre',
        handler: async ({ server }) => {
          await run();

          if (shouldWatch && !closeWatcher) {
            closeWatcher = createContentWatcher(resolvePluginOptions(), run, logger);
          }

          if (serveSearchIndex) {
            server.middlewares.use(pluginOptions.searchIndexRoute || '/static/search', async (req, res) => {
              const options = resolveOptions(resolvePluginOptions());
              const requestUrl = req.url ?? '';
              const match = requestUrl.match(/\/static\/search\/([^/]+)\/index\.json/);
              const locale = match?.[1] ?? options.locales[0]?.locale;
              const localeOptions = options.locales.find((item) => item.locale === locale);

              if (!localeOptions) {
                res.statusCode = 404;
                res.end('Search index locale is not configured.');
                return;
              }

              try {
                const searchIndex = await fs.readFile(localeOptions.searchIndexFile);
                res.setHeader('Content-Type', 'application/json; charset=utf-8');
                res.end(searchIndex);
              } catch {
                res.statusCode = 404;
                res.end('Search index is not generated yet.');
              }
            });
          }
        },
      });

      api.onCloseDevServer(() => {
        if (closeWatcher) {
          closeWatcher();
          closeWatcher = undefined;
        }
      });
    },
  };
}
