import crypto from 'node:crypto';
import { watch, type FSWatcher } from 'node:fs';
import fs from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';

const require = createRequire(import.meta.url);

const NATIVE_BINDING_CANDIDATES = [
  '../garden-content-compiler.node',
  '../garden-content-compiler.darwin-arm64.node',
  '@elecmonkey/garden-content-compiler-darwin-arm64',
  '../garden-content-compiler.linux-x64-gnu.node',
  '@elecmonkey/garden-content-compiler-linux-x64-gnu',
  '../garden-content-compiler.linux-x64-musl.node',
  '@elecmonkey/garden-content-compiler-linux-x64-musl',
] as const;

const PACKAGE_CANDIDATE_PREFIX = '@elecmonkey/garden-content-compiler-';

function nativeBindingLoadError(lastError?: unknown): Error {
  const message = [
    'garden-content-compiler native binding is not built for this platform.',
    'Run `pnpm --filter @elecmonkey/garden-content-compiler build`.',
    `Last lookup: ${displayNativeBindingCandidate(NATIVE_BINDING_CANDIDATES[NATIVE_BINDING_CANDIDATES.length - 1])}`,
  ].join(' ');

  if (lastError instanceof Error && lastError.message) {
    return new Error(`${message} ${lastError.message}`);
  }

  return new Error(message);
}

function displayNativeBindingCandidate(candidate: string): string {
  return candidate.startsWith(PACKAGE_CANDIDATE_PREFIX)
    ? candidate
    : path.basename(candidate);
}

function loadNativeBinding(): NativeBinding {
  let lastError: unknown;

  for (const candidate of NATIVE_BINDING_CANDIDATES) {
    try {
      return require(candidate) as NativeBinding;
    } catch (error) {
      lastError = error;
    }
  }

  return {
    version() {
      return '0.0.0';
    },
    compilePost() {
      throw nativeBindingLoadError(lastError);
    },
    compilePosts() {
      throw nativeBindingLoadError(lastError);
    },
  };
}

const CACHE_VERSION = 1;
const SCHEMA_VERSION = 2;
const DEFAULT_GENERATED_HEADER = '/* This file is generated by @elecmonkey/garden-content-compiler. Do not edit manually. */';

type RsbuildPlugin = {
  name: string;
  enforce: 'pre';
  setup(api: RsbuildPluginApi): void;
};

type RsbuildPluginApi = {
  context: {
    rootPath?: string;
  };
  logger?: Logger;
  onBeforeBuild(hook: HookDescriptor<(params: { isFirstCompile: boolean }) => Promise<void> | void>): void;
  onBeforeStartDevServer(hook: HookDescriptor<(params: { server: DevServer }) => Promise<void> | void>): void;
  onCloseDevServer(hook: () => void): void;
};

type HookDescriptor<T> = {
  order: 'pre';
  handler: T;
};

type DevServer = {
  middlewares: {
    use(route: string, handler: (req: unknown, res: ServerResponseLike) => Promise<void> | void): void;
  };
};

type ServerResponseLike = {
  statusCode: number;
  setHeader(name: string, value: string): void;
  end(body: string | Buffer): void;
};

type Logger = {
  info(message: string): void;
  error(error: unknown): void;
};

export interface JsContentManifest {
  posts: JsPost[];
  publicPosts: JsPost[];
}

export interface JsFrontmatterEntry {
  key: string;
  value: string;
}

export interface JsPost {
  id: string;
  content: string;
  searchContent: string;
  monthFolder: string;
  isDraft: boolean;
  isHidden: boolean;
  title: string;
  date: string;
  description: string;
  tags: string[];
  author: string;
  noToc?: boolean;
  toc: JsTocItem[];
  extra: JsFrontmatterEntry[];
}

export interface JsTocItem {
  id: string;
  text: string;
  level: number;
}

type NativeBinding = {
  compilePost(postFile: string, monthFolder: string): JsPost | null;
  compilePosts(postsDir: string): JsContentManifest;
  version(): string;
};

type NormalizedPost = Omit<JsPost, 'noToc' | 'extra'> & {
  no_toc?: boolean;
  [key: string]: unknown;
};

type PostWithMeta = NormalizedPost & {
  sourceKey: string;
  sourceHash: string;
  contentHash: string;
};

type CacheManifestEntry = {
  slug: string;
  monthFolder: string;
  hash: string;
  contentHash: string;
  cacheFile: string;
};

type CacheManifest = {
  version: number;
  compilerVersion: string;
  schemaVersion: number;
  posts: Record<string, CacheManifestEntry>;
};

type ResolvedGenerateContentOptions = Required<Pick<
  GenerateContentOptions,
  'root' | 'postsDirectory' | 'generatedDirectory' | 'generatedPostsDirectory' | 'outputFile' | 'searchIndexFile' | 'cacheDirectory' | 'typeImport' | 'generatedHeader' | 'log'
>> & {
  cachePostsDirectory: string;
  cacheManifestFile: string;
};

export interface GenerateContentOptions {
  root?: string;
  postsDirectory?: string;
  generatedDirectory?: string;
  generatedPostsDirectory?: string;
  outputFile?: string;
  searchIndexFile?: string;
  cacheDirectory?: string;
  typeImport?: string;
  generatedHeader?: string;
  log?: boolean;
}

export interface GenerateContentResult {
  posts: PostWithMeta[];
  postCount: number;
  compiledCount: number;
  reusedCount: number;
  changedPostModules: number;
  contentChanged: boolean;
  searchChanged: boolean;
  root: string;
  outputFile: string;
  searchIndexFile: string;
  compilerVersion: string;
}

export interface GardenContentPluginOptions extends GenerateContentOptions {
  watch?: boolean;
  serveSearchIndex?: boolean;
  searchIndexRoute?: string;
}

const nativeBinding = loadNativeBinding();

export const compilePost = nativeBinding.compilePost;
export const compilePosts = nativeBinding.compilePosts;
export const version = nativeBinding.version;

function toSearchIndexPost(post: NormalizedPost) {
  return {
    id: post.id,
    title: post.title,
    date: post.date,
    description: post.description,
    tags: post.tags,
    author: post.author,
    content: post.searchContent || '',
  };
}

function normalizePost(post: JsPost): NormalizedPost {
  const {
    monthFolder,
    isDraft,
    isHidden,
    noToc,
    extra = [],
    ...rest
  } = post;

  const extraFields = Object.fromEntries(
    extra.map(({ key, value }) => [key, value]),
  );

  return {
    ...rest,
    monthFolder,
    isDraft,
    isHidden,
    ...(noToc === undefined ? {} : { no_toc: noToc }),
    ...extraFields,
  };
}

function isDraftMarkdown(fileName: string): boolean {
  return fileName.endsWith('.md') && fileName.startsWith('draft-');
}

function isPostMarkdown(fileName: string): boolean {
  return fileName.endsWith('.md') && !isDraftMarkdown(fileName);
}

function fileHash(source: crypto.BinaryLike): string {
  return `sha256:${crypto.createHash('sha256').update(source).digest('hex')}`;
}

function postContentHash(post: NormalizedPost): string {
  const { searchContent: _searchContent, ...generatedPost } = post;
  return fileHash(JSON.stringify(generatedPost));
}

function toPosixPath(value: string): string {
  return value.split(path.sep).join('/');
}

function resolveOptions(options: GenerateContentOptions = {}): ResolvedGenerateContentOptions {
  const root = path.resolve(options.root || process.cwd());
  const postsDirectory = path.resolve(root, options.postsDirectory || 'src/content/posts');
  const generatedDirectory = path.resolve(root, options.generatedDirectory || 'src/generated');
  const generatedPostsDirectory = path.resolve(generatedDirectory, options.generatedPostsDirectory || 'posts');
  const outputFile = path.resolve(generatedDirectory, options.outputFile || 'content.ts');
  const searchIndexFile = path.resolve(generatedDirectory, options.searchIndexFile || 'search-index.json');
  const cacheDirectory = path.resolve(root, options.cacheDirectory || '.garden-cache/content');
  const cachePostsDirectory = path.resolve(cacheDirectory, 'posts');
  const cacheManifestFile = path.resolve(cacheDirectory, 'manifest.json');

  return {
    root,
    postsDirectory,
    generatedDirectory,
    generatedPostsDirectory,
    outputFile,
    searchIndexFile,
    cacheDirectory,
    cachePostsDirectory,
    cacheManifestFile,
    typeImport: options.typeImport || '@/lib/api',
    generatedHeader: options.generatedHeader || DEFAULT_GENERATED_HEADER,
    log: options.log !== false,
  };
}

function toSourceKey(options: ResolvedGenerateContentOptions, filePath: string): string {
  return toPosixPath(path.relative(options.root, filePath));
}

function toCacheFile(slug: string): string {
  return `posts/${slug}.json`;
}

function toGeneratedPostFile(options: ResolvedGenerateContentOptions, slug: string): string {
  return path.join(options.generatedPostsDirectory, `${slug}.ts`);
}

async function pathExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function readJsonFile<T>(filePath: string, fallback: T): Promise<T> {
  try {
    return JSON.parse(await fs.readFile(filePath, 'utf8')) as T;
  } catch {
    return fallback;
  }
}

async function writeFileIfChanged(filePath: string, content: string): Promise<boolean> {
  try {
    const current = await fs.readFile(filePath, 'utf8');
    if (current === content) {
      return false;
    }
  } catch {
    // New file.
  }

  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content);
  return true;
}

async function removeIfExists(filePath: string): Promise<void> {
  try {
    await fs.rm(filePath, { force: true });
  } catch {
    // Nothing to remove.
  }
}

async function scanPostFiles(directory: string): Promise<string[]> {
  const files: string[] = [];
  const entries = await fs.readdir(directory, { withFileTypes: true });

  for (const entry of entries) {
    const entryPath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...await scanPostFiles(entryPath));
      continue;
    }

    if (entry.isFile() && isPostMarkdown(entry.name)) {
      files.push(entryPath);
    }
  }

  return files.sort().reverse();
}

function createEmptyManifest(): CacheManifest {
  return {
    version: CACHE_VERSION,
    compilerVersion: version(),
    schemaVersion: SCHEMA_VERSION,
    posts: {},
  };
}

function isUsableManifest(manifest: unknown): manifest is CacheManifest {
  return Boolean(
    manifest
    && typeof manifest === 'object'
    && (manifest as CacheManifest).version === CACHE_VERSION
    && (manifest as CacheManifest).compilerVersion === version()
    && (manifest as CacheManifest).schemaVersion === SCHEMA_VERSION
    && (manifest as CacheManifest).posts
    && typeof (manifest as CacheManifest).posts === 'object',
  );
}

async function readCachePost(options: ResolvedGenerateContentOptions, cacheFile: string): Promise<NormalizedPost | undefined> {
  const cachePath = path.join(options.cacheDirectory, cacheFile);
  return readJsonFile<NormalizedPost | undefined>(cachePath, undefined);
}

async function writeCachePost(options: ResolvedGenerateContentOptions, cacheFile: string, post: NormalizedPost): Promise<void> {
  const cachePath = path.join(options.cacheDirectory, cacheFile);
  await writeFileIfChanged(cachePath, `${JSON.stringify(post)}\n`);
}

async function buildPostsWithCache(options: ResolvedGenerateContentOptions): Promise<{
  posts: PostWithMeta[];
  compiledCount: number;
  reusedCount: number;
}> {
  const cachedManifest = await readJsonFile<unknown>(options.cacheManifestFile, undefined);
  const previousManifest = isUsableManifest(cachedManifest) ? cachedManifest : createEmptyManifest();
  const nextManifest = createEmptyManifest();
  const postFiles = await scanPostFiles(options.postsDirectory);
  const posts: PostWithMeta[] = [];
  let compiledCount = 0;
  let reusedCount = 0;

  await fs.mkdir(options.cachePostsDirectory, { recursive: true });

  for (const filePath of postFiles) {
    const source = await fs.readFile(filePath);
    const hash = fileHash(source);
    const sourceKey = toSourceKey(options, filePath);
    const monthFolder = path.basename(path.dirname(filePath));
    const previousEntry = previousManifest.posts[sourceKey];
    let post: NormalizedPost | undefined;

    if (previousEntry?.hash === hash) {
      post = await readCachePost(options, previousEntry.cacheFile);
    }

    if (post) {
      reusedCount += 1;
    } else {
      const compiledPost = compilePost(filePath, monthFolder);
      if (!compiledPost) {
        continue;
      }
      post = normalizePost(compiledPost);
      compiledCount += 1;
    }

    const cacheFile = toCacheFile(post.id);
    const contentHash = postContentHash(post);
    await writeCachePost(options, cacheFile, post);

    nextManifest.posts[sourceKey] = {
      slug: post.id,
      monthFolder,
      hash,
      contentHash,
      cacheFile,
    };
    posts.push({ ...post, sourceKey, sourceHash: hash, contentHash });
  }

  const activeCacheFiles = new Set(
    Object.values(nextManifest.posts).map((entry) => entry.cacheFile),
  );

  for (const entry of Object.values(previousManifest.posts)) {
    if (!activeCacheFiles.has(entry.cacheFile)) {
      await removeIfExists(path.join(options.cacheDirectory, entry.cacheFile));
    }
  }

  posts.sort((a, b) => b.date.localeCompare(a.date));
  await writeFileIfChanged(options.cacheManifestFile, `${JSON.stringify(nextManifest, null, 2)}\n`);

  return { posts, compiledCount, reusedCount };
}

function createPostModule(options: ResolvedGenerateContentOptions, postWithMeta: PostWithMeta): string {
  const { searchContent: _searchContent, sourceHash, contentHash, sourceKey: _sourceKey, ...post } = postWithMeta;

  return `${options.generatedHeader}\n\n`
    + `import type { PostData } from '${options.typeImport}';\n\n`
    + `export const postSourceHash = ${JSON.stringify(sourceHash)};\n`
    + `export const postContentHash = ${JSON.stringify(contentHash)};\n\n`
    + `export const post = ${JSON.stringify(post, null, 2)} satisfies PostData;\n`;
}

function createContentModule(options: ResolvedGenerateContentOptions, posts: PostWithMeta[]): string {
  const imports = posts
    .map((post, index) => (
      `import { post as post${index}, postContentHash as post${index}ContentHash, postSourceHash as post${index}SourceHash } from './posts/${post.id}';`
    ))
    .join('\n');
  const postList = posts.map((_post, index) => `  post${index},`).join('\n');
  const hashList = posts
    .map((post, index) => (
      `  ${JSON.stringify(post.id)}: { sourceHash: post${index}SourceHash, contentHash: post${index}ContentHash },`
    ))
    .join('\n');

  return `${options.generatedHeader}\n\n`
    + `import type { PostData } from '${options.typeImport}';\n`
    + `${imports}\n\n`
    + `export const generatedPosts = [\n${postList}\n] satisfies PostData[];\n\n`
    + 'export const generatedPublicPosts = generatedPosts.filter((post) => !post.isHidden);\n\n'
    + `export const generatedPostHashes = {\n${hashList}\n} satisfies Record<string, { sourceHash: string; contentHash: string }>;\n`;
}

async function cleanupStaleGeneratedPosts(options: ResolvedGenerateContentOptions, activeSlugs: Set<string>): Promise<void> {
  if (!await pathExists(options.generatedPostsDirectory)) {
    return;
  }

  const entries = await fs.readdir(options.generatedPostsDirectory, { withFileTypes: true });
  await Promise.all(entries.map(async (entry) => {
    if (!entry.isFile() || !entry.name.endsWith('.ts')) {
      return;
    }

    const slug = entry.name.slice(0, -'.ts'.length);
    if (!activeSlugs.has(slug)) {
      await removeIfExists(path.join(options.generatedPostsDirectory, entry.name));
    }
  }));
}

async function writeGeneratedFiles(options: ResolvedGenerateContentOptions, posts: PostWithMeta[]): Promise<{
  changedPostModules: number;
  contentChanged: boolean;
  searchChanged: boolean;
}> {
  await fs.mkdir(options.generatedPostsDirectory, { recursive: true });

  const activeSlugs = new Set(posts.map((post) => post.id));
  await cleanupStaleGeneratedPosts(options, activeSlugs);

  let changedPostModules = 0;
  for (const post of posts) {
    const changed = await writeFileIfChanged(toGeneratedPostFile(options, post.id), createPostModule(options, post));
    if (changed) {
      changedPostModules += 1;
    }
  }

  const publicPosts = posts.filter((post) => !post.isHidden);
  const searchIndex = publicPosts.map(toSearchIndexPost);
  const contentChanged = await writeFileIfChanged(options.outputFile, createContentModule(options, posts));
  const searchChanged = await writeFileIfChanged(options.searchIndexFile, JSON.stringify(searchIndex));

  return { changedPostModules, contentChanged, searchChanged };
}

export async function generateContent(rawOptions: GenerateContentOptions = {}): Promise<GenerateContentResult> {
  const options = resolveOptions(rawOptions);
  const { posts, compiledCount, reusedCount } = await buildPostsWithCache(options);
  const { changedPostModules, contentChanged, searchChanged } = await writeGeneratedFiles(options, posts);
  const result: GenerateContentResult = {
    posts,
    postCount: posts.length,
    compiledCount,
    reusedCount,
    changedPostModules,
    contentChanged,
    searchChanged,
    root: options.root,
    outputFile: options.outputFile,
    searchIndexFile: options.searchIndexFile,
    compilerVersion: version(),
  };

  if (options.log) {
    console.log(formatContentResult(result));
    if (contentChanged || searchChanged) {
      console.log(`updated indexes: content=${contentChanged}, search=${searchChanged}`);
    }
  }

  return result;
}

function formatContentResult(result: GenerateContentResult): string {
  return `generated ${result.postCount} posts `
    + `(${result.compiledCount} compiled, ${result.reusedCount} cached, ${result.changedPostModules} post modules changed) `
    + `to ${path.relative(result.root, result.outputFile)} and ${path.relative(result.root, result.searchIndexFile)} `
    + `with content compiler ${result.compilerVersion}`;
}

function createContentWatcher(pluginOptions: GenerateContentOptions, run: () => Promise<GenerateContentResult>, logger: Logger): () => void {
  const options = resolveOptions(pluginOptions);
  let timer: ReturnType<typeof setTimeout> | undefined;
  let running = false;
  let pending = false;

  const rerun = () => {
    if (running) {
      pending = true;
      return;
    }

    running = true;
    void run()
      .catch((error: unknown) => {
        logger.error(error);
      })
      .finally(() => {
        running = false;
        if (pending) {
          pending = false;
          rerun();
        }
      });
  };

  const watcher: FSWatcher = watch(options.postsDirectory, { recursive: true }, (_eventType, fileName) => {
    if (!fileName || !fileName.endsWith('.md')) {
      return;
    }

    if (timer) {
      clearTimeout(timer);
    }

    timer = setTimeout(rerun, 80);
  });

  watcher.on('error', (error) => {
    logger.error(error);
  });

  return () => {
    if (timer) {
      clearTimeout(timer);
    }
    watcher.close();
  };
}

export function gardenContentPlugin(rawOptions: GardenContentPluginOptions = {}): RsbuildPlugin {
  const pluginOptions = { ...rawOptions };
  const shouldWatch = pluginOptions.watch !== false;
  const serveSearchIndex = pluginOptions.serveSearchIndex !== false;
  const searchIndexRoute = pluginOptions.searchIndexRoute || '/static/search/index.json';
  let closeWatcher: (() => void) | undefined;

  return {
    name: 'garden-content-plugin',
    enforce: 'pre',
    setup(api) {
      const logger = api.logger || console;
      const resolvePluginOptions = (): GenerateContentOptions => ({
        ...pluginOptions,
        root: pluginOptions.root || api.context.rootPath || process.cwd(),
        log: false,
      });
      const run = async () => {
        const result = await generateContent(resolvePluginOptions());
        logger.info(formatContentResult(result));
        if (result.contentChanged || result.searchChanged) {
          logger.info(`updated indexes: content=${result.contentChanged}, search=${result.searchChanged}`);
        }
        return result;
      };

      api.onBeforeBuild({
        order: 'pre',
        handler: async ({ isFirstCompile }) => {
          if (!isFirstCompile) {
            return;
          }
          await run();
        },
      });

      api.onBeforeStartDevServer({
        order: 'pre',
        handler: async ({ server }) => {
          await run();

          if (shouldWatch && !closeWatcher) {
            closeWatcher = createContentWatcher(resolvePluginOptions(), run, logger);
          }

          if (serveSearchIndex) {
            server.middlewares.use(searchIndexRoute, async (_req, res) => {
              const options = resolveOptions(resolvePluginOptions());
              try {
                const searchIndex = await fs.readFile(options.searchIndexFile);
                res.setHeader('Content-Type', 'application/json; charset=utf-8');
                res.end(searchIndex);
              } catch {
                res.statusCode = 404;
                res.end('Search index is not generated yet.');
              }
            });
          }
        },
      });

      api.onCloseDevServer(() => {
        if (closeWatcher) {
          closeWatcher();
          closeWatcher = undefined;
        }
      });
    },
  };
}
